name: CD

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise – MPN'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep build --file code/main.bicep'

    - publish: '$(Build.SourcesDirectory)/code/main.json'
      displayName: 'Publish template'
      artifact: drop



